export default {
  //AppIcon
  // appIcon: require('../assets/images/icons/pokemonAppIcon.png'),
  appIcon: require('../assets/images/icons/pokeAppIcon.png'),

  //Icons
  addEventsIcon: require('../assets/images/icons/addEventsIcon.png'),
  cancelIcon: require('../assets/images/icons/cancelIcon.png'),
  rightArrowCircle: require('../assets/images/icons/arrow_circle_right.png'),
  cameraIcon: require('../assets/images/icons/cameraIcon.png'),
  calendarIcon: require('../assets/images/icons/calendarIcon.png'),
  calendarIcon2: require('../assets/images/icons/calendarIcon2.png'),
  notificationsOnIcon: require('../assets/images/icons/notificationsOnIcon.png'),
  notificationsOffIcon1: require('../assets/images/icons/notificationsOffIcon1.png'),
  notificationsOffIcon2: require('../assets/images/icons/notificationsOffIcon2.png'),
  leftChevronIcon: require('../assets/images/icons/leftChevronIcon.png'),
  rightChevronIcon: require('../assets/images/icons/rightChevronIcon.png'),
  checkmarkOnIcon: require('../assets/images/icons/checkmarkOnIcon.png'),
  checkmarkOffIcon: require('../assets/images/icons/checkmarkOffIcon.png'),
  addIcon: require('../assets/images/icons/addIcon.png'),
  minusIcon: require('../assets/images/icons/minusIcon.png'),
  shinyIcon: require('../assets/images/icons/shinyIcon.png'),
  ashCapIcon: require('../assets/images/icons/ashCapIcon.png'),
  fieldResearchIcon: require('../assets/images/icons/fieldResearchIcon.png'),
  pokeEggIcon: require('../assets/images/icons/pokeEggIcon.png'),
  twoKmEggIcon: require('../assets/images/icons/2KmEgg.png'),
  fiveKmEggIcon: require('../assets/images/icons/5KmEgg.png'),
  sevenKmEggIcon: require('../assets/images/icons/7KmEgg.png'),
  tenKmEggIcon: require('../assets/images/icons/10KmEgg.png'),
  twelveKmEggIcon: require('../assets/images/icons/12KmEgg.png'),
  raidIcon: require('../assets/images/icons/raidIcon.png'),
  darkModeIcon: require('../assets/images/icons/darkModeIcon.png'),
  brightModeIcon: require('../assets/images/icons/brightModeIcon.png'),
  greenArrowIcon1: require('../assets/images/icons/greenArrow1.png'),
  greenArrowIcon2: require('../assets/images/icons/greenArrow2.png'),
  greenArrowIcon3: require('../assets/images/icons/greenArrow3.png'),
  blackArrowIcon: require('../assets/images/icons/blackArrowIcon.png'),
  candyIcon: require('../assets/images/icons/candyIcon.png'),
  redoIcon: require('../assets/images/icons/redoIcon.png'),
  infoIcon: require('../assets/images/icons/ibutton.png'),
  questionMarkIcon: require('../assets/images/icons/questionmark.png'),
  serverErrorIcon: require('../assets/images/icons/serverErrorIcon.png'),
  shadowIcon: require('../assets/images/icons/shadowIcon.png'),
  shareIcon: require('../assets/images/icons/shareIcon.png'),
  deleteIcon: require('../assets/images/icons/deleteIcon.png'),
  pikaGPTIcon: require('../assets/images/icons/pikaGPTIcon.png'),
  pikaFace: require('../assets/images/icons/pokemonAppIcon.png'),
  emojiIconOutline: require('../assets/images/icons/emojiIconOutline.png'),
  emojiIconFilled: require('../assets/images/icons/emojiIconFilled.png'),
  plusIcon: require('../assets/images/icons/plusIcon.png'),
  speakerIconNormal: require('../assets/images/icons/speakerIconNormal.png'),
  speakerIconHighlighted: require('../assets/images/icons/speakerIconHighlighted.png'),
  searchIcon: require('../assets/images/icons/searchIcon.png'),
  rotomIcon: require('../assets/images/icons/rotomIcon.png'),
  pokeBallIcon: require('../assets/images/icons/pokeBallIcon.png'),
  masterBallIcon: require('../assets/images/icons/masterBallIcon.png'),
  mikeOnIcon: require('../assets/images/icons/mikeOn.png'),
  mikeOffIcon: require('../assets/images/icons/mikeOff.png'),
  sendIcon: require('../assets/images/icons/sendIcon.png'),
  teamRocketRadarLeaders: require('../assets/images/icons/teamRocketRadarLeaders.png'),
  teamRocketRadarGiovanni: require('../assets/images/icons/teamRocketRadarGiovanni.png'),
  teamRocketRadarGrunt: require('../assets/images/icons/teamRocketRadarGrunt.png'),
  Giovanni: require('../assets/images/icons/Giovanni.png'),
  Cliff: require('../assets/images/icons/Cliff.png'),
  Sierra: require('../assets/images/icons/Sierra.png'),
  Arlo: require('../assets/images/icons/Arlo.png'),
  femaleGrunt: require('../assets/images/icons/femaleGrunt.png'),
  maleGrunt: require('../assets/images/icons/maleGrunt.png'),
  pokeCalculatorIcon: require('../assets/images/icons/pokeCalculatorIcon.png'),
  pokeCalculatorIcon2: require('../assets/images/icons/pokeCalculatorIcon2.png'),
  vsIcon1: require('../assets/images/icons/vsIcon1.png'),
  vsIcon2: require('../assets/images/icons/vsIcon2.png'),

  //Images
  calendar1: require('../assets/images/calendar.png'),
  calendar2: require('../assets/images/calendar2.png'),
  calendar3: require('../assets/images/calendar3.png'),
  time: require('../assets/images/time.png'),
  pokemonBanner: require('../assets/images/pokemonBanner.jpg'),
  noImage: require('../assets/images/no_image.png'),
  noInternetImage: require('../assets/images/pichu.jpeg'),
  noDateSelectedPromptImage1: require('../assets/images/cutePika1.png'),
  noDateSelectedPromptImage2: require('../assets/images/cutePika2.png'),

  //Illustrations
  calendarIllustration1: require('../assets/images/illustrations/calendarIllustration1.png'),
  calendarIllustration2: require('../assets/images/illustrations/calendarIllustration2.png'),
  calendarIllustration3: require('../assets/images/illustrations/calendarIllustration3.png'),
  calendarIllustration4: require('../assets/images/illustrations/calendarIllustration4.png'),
  fieldResearchIllustration: require('../assets/images/illustrations/fieldResearchIllustration.jpeg'),

  //gifs
  pichuDancing: require('../assets/images/gifs/pichuGif.webp'),
  togepiGif: require('../assets/images/gifs/togepiGif.gif'),
  arceusGif: require('../assets/images/gifs/arceusGif.gif'),
};
