export default {
  app_name: 'Poke Event Guide',
  continue: 'Continue',
  no_event_today: 'No events',
  no_event_added: 'No event added',
  viewEvents: 'View Events',
  addEvent: 'Add Event',
  cancel: 'cancel',
  save: 'save',
  close: 'close',
  event_name: 'Event Name',
  event_date: 'Event Date',
  event_time: 'Event Time',
  sample_event_name: 'Charizard Raid',
  sample_event_date: '01-01-2023',
  compulsorySign: ' *',
  events_today: 'Events on',
  no_event_string: 'There is no event for the day',
  event_ranges_from: 'Event Ranges from',
  no_images_available: 'No Images Available',
  number_of_events: 'Number of events',
  plus: '+',
  event_completed: 'Event Completed',
  ok: 'ok',
  select_date_prompt: 'Please select a date to view the events',
  version: 'Version',
  version_number: '1.0',
  futureImplementations: 'Upcoming implementations',
};
