export default {
  normal: 'https://leekduck.com/assets/img/types/normal.png',
  fire: 'https://leekduck.com/assets/img/types/fire.png',
  water: 'https://leekduck.com/assets/img/types/water.png',
  electric: 'https://leekduck.com/assets/img/types/electric.png',
  grass: 'https://leekduck.com/assets/img/types/grass.png',
  ice: 'https://leekduck.com/assets/img/types/ice.png',
  fighting: 'https://leekduck.com/assets/img/types/fighting.png',
  poison: 'https://leekduck.com/assets/img/types/poison.png',
  ground: 'https://leekduck.com/assets/img/types/ground.png',
  flying: 'https://leekduck.com/assets/img/types/flying.png',
  psychic: 'https://leekduck.com/assets/img/types/psychic.png',
  bug: 'https://leekduck.com/assets/img/types/bug.png',
  rock: 'https://leekduck.com/assets/img/types/rock.png',
  ghost: 'https://leekduck.com/assets/img/types/ghost.png',
  dragon: 'https://leekduck.com/assets/img/types/dragon.png',
  dark: 'https://leekduck.com/assets/img/types/dark.png',
  steel: 'https://leekduck.com/assets/img/types/steel.png',
  fairy: 'https://leekduck.com/assets/img/types/fairy.png',
};
